version: "3.9"

networks:
  wpp_internal_net:
    driver: bridge

services:
  whatsapp:
    build: ./whatsapp
    container_name: whatsapp-server
    restart: always
    networks:
      - wpp_internal_net
    volumes:
      - ./whatsapp/wwebjs_auth:/home/node/app/wwebjs_auth
    ports:
      - "3000:3000"
