version: "3.9"

networks:
  wpp_internal_net:
    driver: bridge

services:
  whatsapp:
    build: ./whatsapp
    container_name: whatsapp-server
    restart: always
    networks:
      - wpp_internal_net
    ports:
      - "3001:3000"        # Puerto externo 3001 â†’ interno 3000
    volumes:
      - ./wwebjs_auth:/home/node/app/wwebjs_auth